### ISSUE TITLE
Improve compatibility with MicroPython re. "base64" module

### ISSUE THREAD

**Issue by amotl** [smlng/pycayennelpp#63]
Dear Sebastian,

while we have included the `base64` module within our [Terkin Datalogger](https://github.com/hiveeyes/terkin-datalogger), this module is not part of the MicroPython standard library.

We could pull the respective `import base64` statement into the `LppFrame.from_base64` class method in order to provide all the other features, even when not having installed `base64` at all.

This is really just a nit you might want to consider within the next release.

Thanks again and with kind regards,
Andreas.

**Comment by smlng** [comment]
yeah, I originally put it in because I developed pycayennelpp when working with TheThingsNetwork (TTN) and Python, and the payload which I got from TTN in python was base64 encoded - so this function was handy. However, thinking about it now the same reason as with the unix timestamp and `datetime` applies here too, i.e., the use could do the decoding.

So I agree, to remove this dependency completely and rather add documentation (+ examples) on how to handle this. However, this would also introduce an API change, breaking backwards compatibility. So this is something for release 2.0.0, for which I plan some more changes anyway.
